import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs/promises';
import path from 'node:path';
import { productVideoHarness, makeProposal, sineWav, waitForVoiceovers } from './helpers/productVideoHarness.ts';
import { createProductVideoVerificationPng } from '../electron/core/productVideoVerificationImage.ts';
import { buildVideoEditorV2RemotionComposition } from '../shared/videoAutoEditRemotion.ts';
const picture = () => `data:image/png;base64,${createProductVideoVerificationPng('GF-ABC123DEF456').toString('base64')}`;

test('real SQLite approvals invalidate immediately, recover on load and never authorize old proposals', async (t) => {
    const h = await productVideoHarness(); t.after(() => h.close());
    const bundle = await h.store.upsertProduct({ name: '测试商品', images: [{ dataUrl: picture() }] });
    const product = await h.store.getProductCreativeReference(bundle.product.id);
    const proposal = makeProposal(product);
    await h.approveFixture(proposal);
    assert.equal((await h.api.getProductVideoApprovalRequest('session-1')).status, 'pending');
    assert.equal(h.state.ttsCalls, 0);
    await h.store.upsertSku({ productId: product.id, name: '新规格' });
    h.restart();
    assert.equal(h.api.getPendingToolApproval('approval-1').status, 'invalidated');
    assert.equal(h.state.tasks.get('task-approval-1').status, 'cancelled');
    assert.equal((await h.api.getProductVideoApprovalRequest('session-1')).invalidation.reason, 'product-updated');
    assert.equal((await h.api.resolveProductVideoApproval('approval-1', true)).status, 'invalidated');
    assert.equal(await h.api.findProductVideoProjectByProposalId(proposal.proposalId), null);
    assert.equal(h.state.videoCalls + h.state.ttsCalls, 0);
    assert.equal((await h.approveFixture(proposal)).approval.status, 'invalidated');
    await assert.rejects(h.api.getProductVideoReplanInput('different-session', 'approval-1'), /属于/);
    const retry = await h.api.getProductVideoReplanInput('session-1', 'approval-1');
    assert.equal(retry.message, '给这个商品做一个视频');
    assert.equal(retry.productId, product.id);
    const newest = await h.store.getProductCreativeReference(product.id);
    await h.approveFixture(makeProposal(newest, 'proposal-newest'), 'approval-2');
    h.sql.prepare("UPDATE pending_tool_approvals SET params_json = ? WHERE call_id = 'approval-2'").run(JSON.stringify(proposal));
    await h.api.reconcileProductVideoApprovals();
    assert.equal(h.api.getPendingToolApproval('approval-2').status, 'invalidated');
    h.state.spaceId = 'other';
    assert.equal(await h.api.getProductVideoApprovalRequest('session-1'), null);
    await assert.rejects(h.api.getProductVideoReplanInput('session-1', 'approval-2'), /空间/);
    h.state.spaceId = 'default';
    const same = await h.store.getProductCreativeReference(product.id);
    await h.approveFixture(makeProposal(same, 'proposal-delete'), 'approval-3');
    await h.store.deleteProduct(product.id);
    assert.equal((await h.api.getProductVideoApprovalRequest('session-1')).invalidation.reason, 'product-deleted');
});

test('pure images create one durable project; real TTS jobs, audio replacement and export share the timeline', async (t) => {
    const h = await productVideoHarness(); t.after(() => h.close());
    const bundle = await h.store.upsertProduct({ name: '实拍商品', images: [{ dataUrl: picture() }] });
    const product = await h.store.getProductCreativeReference(bundle.product.id);
    const proposal = makeProposal(product);
    await h.approveFixture(proposal);
    const resolutions = await Promise.all([h.api.resolveProductVideoApproval('approval-1', true), h.api.resolveProductVideoApproval('approval-1', true)]);
    assert.equal(resolutions[0].success, true, resolutions[0].error);
    assert.ok(['completed', 'executing'].includes(resolutions[1].status));
    assert.equal((await h.api.resolveProductVideoApproval('approval-1', true)).projectId, resolutions[0].projectId);
    const id = resolutions[0].projectId;
    let project = await h.api.getVideoEditorV2Project(id);
    assert.equal(project.productVideo.scenes.length, 5);
    assert.equal(h.state.videoCalls, 0);
    assert.equal(h.state.ttsCalls, 0);
    h.state.settings = { tts_endpoint: 'https://tts.invalid/v1', tts_api_key: 'fixture', tts_model: 'tts-1' };
    h.state.audio = sineWav(1.2);
    await Promise.all([h.api.submitApprovedProductVideoVoiceovers(id), h.api.submitApprovedProductVideoVoiceovers(id)]);
    project = await waitForVoiceovers(h.api, id);
    assert.equal(h.state.ttsCalls, 5);
    assert.ok(project.productVideo.scenes.every((scene: any) => scene.voiceoverStatus === 'ready'));
    assert.equal(project.timeline.tracks.find((track: any) => track.kind === 'voiceover').clips.length, 5);
    assert.equal((await new h.api.MediaGenerationJobRegistry().listJobs({ source: 'product-video-voiceover' })).items.length, 5);
    await h.api.submitApprovedProductVideoVoiceovers(id);
    assert.equal(h.state.ttsCalls, 5);
    h.restart();
    project = await h.api.reconcileProductVideoVoiceoverProject(id);
    assert.equal(project.timeline.tracks.find((track: any) => track.kind === 'voiceover').clips.length, 5);
    assert.equal(h.state.ttsCalls, 5);
    const bgm = path.join(h.root, 'bgm.wav'); await fs.writeFile(bgm, sineWav(15, 220));
    await h.api.setProductVideoMusic({ projectId: id, sourcePath: bgm });
    const recording = path.join(h.root, 'recording.wav'); await fs.writeFile(recording, sineWav(4));
    project = await h.api.attachProductVideoVoiceoverAsset({ projectId: id, sceneId: 'scene-0', absolutePath: recording, source: 'imported' });
    assert.equal(project.productVideo.scenes[0].voiceoverStatus, 'duration-conflict');
    assert.equal(project.timeline.tracks.find((track: any) => track.kind === 'voiceover').clips.length, 4);
    project = await h.api.applyProductVideoEditCommand({ projectId: id, command: { type: 'scene.duration', sceneId: 'scene-0', durationMs: 4500 } });
    assert.equal(project.productVideo.scenes[0].voiceoverStatus, 'ready');
    await h.api.applyProductVideoEditCommand({ projectId: id, command: { type: 'scene.reorder', sceneId: 'scene-0', targetSceneId: 'scene-4', position: 'after' } });
    await h.api.applyProductVideoEditCommand({ projectId: id, command: { type: 'scene.text', sceneId: 'scene-1', text: '修改后的商品说明' } });
    project = await h.api.getVideoEditorV2Project(id);
    const composition = buildVideoEditorV2RemotionComposition(project);
    assert.ok(composition.scenes.some((scene: any) => scene.id.startsWith('voiceover_') && scene.volume === 1));
    assert.ok(composition.scenes.some((scene: any) => scene.id.startsWith('music_') && scene.volume === 0.2));
    const output = await h.api.renderVideoEditorV2Project({ projectId: id, renderVideo: false });
    await fs.access(output.compositionPath);
    assert.equal(h.state.videoCalls, 0);
    await h.store.deleteProduct(product.id);
    project = await h.api.getVideoEditorV2Project(id);
    await fs.access(project.assets[0].projectPath);
    assert.equal((await h.api.resolveProductVideoApproval('approval-1', true)).projectId, id);
    if (process.env.GARDENFLOW_PRODUCT_VIDEO_RENDER_QA_DIR) {
        const dir = path.resolve(process.env.GARDENFLOW_PRODUCT_VIDEO_RENDER_QA_DIR);
        await fs.mkdir(dir, { recursive: true });
        const rendered = await h.api.renderVideoEditorV2Project({ projectId: id, outputPath: path.join(dir, 'pure-images-dual-audio.mp4') });
        await fs.writeFile(path.join(dir, 'render-result.json'), JSON.stringify(rendered, null, 2));
    }
});

test('cancel submits nothing; failed speech stays isolated and edits/removal can be undone', async (t) => {
    const h = await productVideoHarness(); t.after(() => h.close());
    h.state.settings = { tts_endpoint: 'https://tts.invalid/v1', tts_api_key: 'fixture', tts_model: 'tts-1' };
    h.state.audio = sineWav(1);
    const bundle = await h.store.upsertProduct({ name: '声音验收', images: [{ dataUrl: picture() }] });
    const product = await h.store.getProductCreativeReference(bundle.product.id);
    await h.approveFixture(makeProposal(product, 'cancelled'));
    assert.equal((await h.api.resolveProductVideoApproval('approval-1', false)).status, 'cancelled');
    assert.equal(h.state.ttsCalls, 0);
    assert.equal(await h.api.findProductVideoProjectByProposalId('cancelled'), null);
    h.state.failSpeech = true;
    const proposal = makeProposal(product, 'speech-failure');
    proposal.scenes.slice(1).forEach((scene) => { scene.overlayText = ''; });
    await h.approveFixture(proposal, 'approval-2');
    const result = await h.api.resolveProductVideoApproval('approval-2', true);
    assert.equal(result.success, true);
    let project = await waitForVoiceovers(h.api, result.projectId);
    assert.equal(project.productVideo?.scenes[0].voiceoverStatus, 'failed');
    assert.ok(project.productVideo?.scenes.slice(1).every((scene) => scene.voiceoverStatus === 'not-required'));
    assert.equal(h.state.ttsCalls, 1);
    await h.api.submitApprovedProductVideoVoiceovers(project.id);
    assert.equal(h.state.ttsCalls, 1, 'failed automatic speech must not be resubmitted');
    h.state.failSpeech = false;
    await h.api.submitProductVideoSceneVoiceover({ projectId: project.id, sceneId: 'scene-0' });
    project = await waitForVoiceovers(h.api, project.id);
    assert.equal(project.productVideo?.scenes[0].voiceoverStatus, 'ready');
    assert.equal(h.state.ttsCalls, 2);
    project = await h.api.applyProductVideoEditCommand({ projectId: project.id, command: { type: 'scene.narration-text', sceneId: 'scene-0', text: '新的文案' } });
    assert.equal(project.productVideo?.scenes[0].voiceoverStatus, 'stale');
    assert.equal(project.timeline.tracks.find((track) => track.kind === 'voiceover')?.clips.length, 1, 'stale speech remains previewable until explicitly replaced');
    await h.api.submitApprovedProductVideoVoiceovers(project.id);
    assert.equal(h.state.ttsCalls, 2);
    project = await h.api.undoVideoEditorV2ProjectTimeline({ projectId: project.id });
    assert.equal(project.productVideo?.scenes[0].voiceoverStatus, 'ready');
    await h.api.applyProductVideoEditCommand({ projectId: project.id, command: { type: 'voiceover.remove', sceneId: 'scene-0' } });
    project = await h.api.undoVideoEditorV2ProjectTimeline({ projectId: project.id });
    assert.equal(project.timeline.tracks.find((track) => track.kind === 'voiceover')?.clips.length, 1);
});

test('catalog writes during snapshot preparation abort creation before any generation job', async (t) => {
    const h = await productVideoHarness(); t.after(() => h.close());
    const bundle = await h.store.upsertProduct({ name: '并发验收', images: [{ dataUrl: picture() }] });
    const product = await h.store.getProductCreativeReference(bundle.product.id);
    const proposal = makeProposal(product);
    let mutation: Promise<unknown>;
    const snapshot = h.store.withProductCreativeSnapshot(product.id, product.updatedAt, async (_: unknown, assets: any, assertCurrent: () => void) => {
        return h.api.createProductVideoProject({ proposal, sourceAssets: assets, productSnapshot: product,
            assertSnapshotCurrent: () => {
                mutation = h.store.upsertSku({ productId: product.id, name: '采集同时写入' });
                assertCurrent();
            },
        });
    });
    await assert.rejects(snapshot, { code: 'PRODUCT_SNAPSHOT_CHANGED' });
    await mutation!;
    assert.equal(await h.api.findProductVideoProjectByProposalId(proposal.proposalId), null);
    assert.equal(h.state.ttsCalls + h.state.videoCalls, 0);
});

test('legacy projects never auto-submit speech and a restarted interrupted job requires manual retry', async (t) => {
    const h = await productVideoHarness(); t.after(() => h.close());
    h.state.audio = sineWav(1);
    const bundle = await h.store.upsertProduct({ name: '恢复验收', images: [{ dataUrl: picture() }] });
    const product = await h.store.getProductCreativeReference(bundle.product.id);
    const proposal = makeProposal(product);
    proposal.scenes.slice(1).forEach((scene) => { scene.overlayText = ''; });
    await h.approveFixture(proposal);
    const result = await h.api.resolveProductVideoApproval('approval-1', true);
    let project = await h.api.getVideoEditorV2Project(result.projectId);
    delete project.productVideo.voiceoverAutoApprovedAt;
    await h.api.saveVideoEditorV2Project(project);
    h.state.settings = { tts_endpoint: 'https://tts.invalid/v1', tts_api_key: 'fixture', tts_model: 'tts-1' };
    await h.api.submitApprovedProductVideoVoiceovers(project.id);
    assert.equal(h.state.ttsCalls, 0);
    await h.api.submitProductVideoSceneVoiceover({ projectId: project.id, sceneId: 'scene-0' });
    project = await waitForVoiceovers(h.api, project.id);
    const scene = project.productVideo.scenes[0];
    const jobFile = path.join(h.root, 'default/.gardenflow/media-runtime/media-jobs.json');
    const jobs = JSON.parse(await fs.readFile(jobFile, 'utf8'));
    const job = jobs.jobs.find((item: any) => item.jobId === scene.voiceoverJobId);
    job.status = 'running'; job.createdAt = '2020-01-01T00:00:00.000Z'; job.artifacts = [];
    await fs.writeFile(jobFile, JSON.stringify(jobs));
    scene.voiceoverAttachedJobId = undefined; scene.voiceoverStatus = 'generating';
    await h.api.saveVideoEditorV2Project(project);
    h.restart();
    project = await h.api.reconcileProductVideoVoiceoverProject(project.id);
    assert.equal(project.productVideo.scenes[0].voiceoverStatus, 'failed');
    assert.match(project.productVideo.scenes[0].voiceoverError, /重启/);
    assert.equal(h.state.ttsCalls, 1);
});
