const identity = {
  "schemaVersion": 1,
  "displayName": "GardenFlow",
  "slug": "gardenflow",
  "appId": "com.gardenflow.app",
  "nativeHost": "com.gardenflow.browser_control",
  "assetProtocol": "gardenflow-asset",
  "database": "gardenflow.db",
  "workspaceDirectory": ".gardenflow",
  "repository": "Garden12138/garden-flow",
  "updatesEnabled": false,
  "legacy": {
    "userDataNames": [
      "red-convert-desktop",
      "Bojin",
      "Beav",
      "RedBox",
      "RedConvert",
      "redconvert-desktop",
      "com.redbox.app"
    ],
    "displayNames": [
      "Bojin",
      "博今",
      "RedBox",
      "RedClaw"
    ],
    "browserExtensionExportPaths": [
      "red-convert-desktop/integrations/browser-extension/redbox-capture"
    ],
    "database": "redconvert.db",
    "workspaceDirectory": ".redconvert",
    "projectDirectory": "redclaw",
    "nativeHost": "com.redbox.browser_control",
    "assetProtocols": [
      "redbox-asset",
      "local-file"
    ],
    "videoEndpoint": "https://api.ziz.hk/bojin/v1",
    "keys": {
      "__REDBOX_CAPTURE_RUNTIME__": "__GARDENFLOW_CAPTURE_RUNTIME__",
      "__REDBOX_WECHAT_IMAGE_": "__GARDENFLOW_WECHAT_IMAGE_",
      "__REDBOX_XHS_BRIDGE_INSTALLED__": "__GARDENFLOW_XHS_BRIDGE_INSTALLED__",
      "__REDBOX_XHS_RESPONSES__": "__GARDENFLOW_XHS_RESPONSES__",
      "__RED_ELECTRON_IPC__": "__GARDENFLOW_ELECTRON_IPC__",
      "__redboxGenericCaptureListenerV1__": "__gardenflowGenericCaptureListenerV1__",
      "__redboxGlobalClipboardWatcher": "__gardenflowGlobalClipboardWatcher",
      "__redboxPageRouteBridgeInstalled__": "__gardenflowPageRouteBridgeInstalled__",
      "__redboxXhsMethod": "__gardenflowXhsMethod",
      "__redboxXhsUrl": "__gardenflowXhsUrl",
      "__redbox_ipc_timeout__": "__gardenflow_ipc_timeout__",
      "advisorRedClawOrder": "advisorGardenFlowOrder",
      "beav": "gardenflow",
      "bojin": "gardenflow",
      "bojinRoute": "gardenflowRoute",
      "bojinVideo": "gardenflowVideo",
      "bojin_official_auto": "gardenflow_official_auto",
      "buildRedClawAuthoringMessage": "buildGardenFlowAuthoringMessage",
      "buildRedClawAuthoringPrompt": "buildGardenFlowAuthoringPrompt",
      "buildRedClawContextId": "buildGardenFlowContextId",
      "buildRedClawInitialContext": "buildGardenFlowInitialContext",
      "buildRedClawRuntimeMetadata": "buildGardenFlowRuntimeMetadata",
      "buildRedClawSessionTitle": "buildGardenFlowSessionTitle",
      "cancelRedClawTask": "cancelGardenFlowTask",
      "clearPendingRedClawMessage": "clearPendingGardenFlowMessage",
      "clearRedClawNavigationAction": "clearGardenFlowNavigationAction",
      "coerceToRedboxAssetUrl": "coerceToGardenFlowAssetUrl",
      "compactRedClawContext": "compactGardenFlowContext",
      "completeRedClawInitialization": "completeGardenFlowInitialization",
      "completeRedClawStyleDefinition": "completeGardenFlowStyleDefinition",
      "confirmRedClawTask": "confirmGardenFlowTask",
      "createAdvisorFromRedClaw": "createAdvisorFromGardenFlow",
      "createRedClawBridge": "createGardenFlowBridge",
      "createRedClawComposerShortcuts": "createGardenFlowComposerShortcuts",
      "createRedClawComposerShortcutsForContext": "createGardenFlowComposerShortcutsForContext",
      "createRedClawProject": "createGardenFlowProject",
      "createRedClawTask": "createGardenFlowTask",
      "createRoomFromRedClaw": "createRoomFromGardenFlow",
      "deleteRoomFromRedClaw": "deleteRoomFromGardenFlow",
      "endpointWasAssignedByWrongBojinMigration": "endpointWasAssignedByWrongGardenFlowMigration",
      "ensureMainRedClawSession": "ensureMainGardenFlowSession",
      "ensureRedClawOnboardingCompletedWithDefaults": "ensureGardenFlowOnboardingCompletedWithDefaults",
      "ensureRedClawProfileFiles": "ensureGardenFlowProfileFiles",
      "formatWanderVisualBlocksForRedClaw": "formatWanderVisualBlocksForGardenFlow",
      "getBojinOfficialVideoModel": "getGardenFlowOfficialVideoModel",
      "getRedClawBackgroundRunner": "getGardenFlowBackgroundRunner",
      "getRedClawBackgroundRunnerLazy": "getGardenFlowBackgroundRunnerLazy",
      "getRedClawCompactTargetTokens": "getGardenFlowCompactTargetTokens",
      "getRedClawCompactThreshold": "getGardenFlowCompactThreshold",
      "getRedClawImageJobCompletedCount": "getGardenFlowImageJobCompletedCount",
      "getRedClawImageJobExpectedCount": "getGardenFlowImageJobExpectedCount",
      "getRedClawImageJobOverallProgress": "getGardenFlowImageJobOverallProgress",
      "getRedClawImageJobTitle": "getGardenFlowImageJobTitle",
      "getRedClawProject": "getGardenFlowProject",
      "getRedClawProjectContextPrompt": "getGardenFlowProjectContextPrompt",
      "handleRedClawExecutionStateChange": "handleGardenFlowExecutionStateChange",
      "handleRedClawOnboardingTurn": "handleGardenFlowOnboardingTurn",
      "handleRedclaw": "handleGardenFlow",
      "handleRedclawProfileDraftChange": "handleGardenFlowProfileDraftChange",
      "handleRedclawTaskEvent": "handleGardenFlowTaskEvent",
      "hasRedboxVideoDirector": "hasGardenFlowVideoDirector",
      "initializeRedClawBackgroundRunner": "initializeGardenFlowBackgroundRunner",
      "installBojinCaptureRuntime": "installGardenFlowCaptureRuntime",
      "isBojinCompatibleEndpoint": "isGardenFlowCompatibleEndpoint",
      "isBojinOfficialVideoModel": "isGardenFlowOfficialVideoModel",
      "isCurrentRedClawContext": "isCurrentGardenFlowContext",
      "isFirstRedClawTurn": "isFirstGardenFlowTurn",
      "isRedClawChatExecuting": "isGardenFlowChatExecuting",
      "isRedClawOnboardingCompleted": "isGardenFlowOnboardingCompleted",
      "isRedboxAssetUrl": "isGardenFlowAssetUrl",
      "isRedclawProfileLoading": "isGardenFlowProfileLoading",
      "isWindowsRedClaw": "isWindowsGardenFlow",
      "keepRedClawAlive": "keepGardenFlowAlive",
      "listRedClawProjects": "listGardenFlowProjects",
      "listRedClawTasks": "listGardenFlowTasks",
      "loadRedClawProfilePromptBundle": "loadGardenFlowProfilePromptBundle",
      "loadRedClawProjectContext": "loadGardenFlowProjectContext",
      "loadRedclawProfileBundle": "loadGardenFlowProfileBundle",
      "mapRedclawTaskEventToNotification": "mapGardenFlowTaskEventToNotification",
      "model_name_redclaw": "model_name_gardenflow",
      "msg_redclaw_auto_": "msg_gardenflow_auto_",
      "msg_redclaw_hb_": "msg_gardenflow_hb_",
      "nav_to_redclaw": "nav_to_gardenflow",
      "navigateToRedClaw": "navigateToGardenFlow",
      "navigateToRedClawWithKnowledge": "navigateToGardenFlowWithKnowledge",
      "normalizeRedClawAuthoringHints": "normalizeGardenFlowAuthoringHints",
      "normalizeRedClawPlatform": "normalizeGardenFlowPlatform",
      "normalizeRedClawSourceMode": "normalizeGardenFlowSourceMode",
      "normalizeRedClawSpaceListPayload": "normalizeGardenFlowSpaceListPayload",
      "normalizeRedClawTaskType": "normalizeGardenFlowTaskType",
      "nredclaw": "ngardenflow",
      "onNavigateToRedClaw": "onNavigateToGardenFlow",
      "onOpenRedClawOnboarding": "onOpenGardenFlowOnboarding",
      "onOpenRedClawSession": "onOpenGardenFlowSession",
      "onSelectRedClaw": "onSelectGardenFlow",
      "openNoteInRedClaw": "openNoteInGardenFlow",
      "openRedClawChatSurface": "openGardenFlowChatSurface",
      "openRedClawOnboarding": "openGardenFlowOnboarding",
      "openRedClawSession": "openGardenFlowSession",
      "openVideoInRedClaw": "openVideoInGardenFlow",
      "pendingRedClawMessage": "pendingGardenFlowMessage",
      "previewRedClawTask": "previewGardenFlowTask",
      "readInitialRedClawAiSurface": "readInitialGardenFlowAiSurface",
      "readRedClawLastSessionId": "readGardenFlowLastSessionId",
      "redClawAuthoringHints": "gardenFlowAuthoringHints",
      "redClawAutomationDraftFromItem": "gardenFlowAutomationDraftFromItem",
      "redClawAutomationIntentFromDraft": "gardenFlowAutomationIntentFromDraft",
      "redClawAutomationIsTask": "gardenFlowAutomationIsTask",
      "redClawAutomationScheduleToCron": "gardenFlowAutomationScheduleToCron",
      "redClawAutomationScheduledPayload": "gardenFlowAutomationScheduledPayload",
      "redClawAutomationWeekdayLabel": "gardenFlowAutomationWeekdayLabel",
      "redClawCompactTargetTokens": "gardenFlowCompactTargetTokens",
      "redClawGlobalSidebarContent": "gardenFlowGlobalSidebarContent",
      "redClawLastSessionStorageKey": "gardenFlowLastSessionStorageKey",
      "redClawNavigationAction": "gardenFlowNavigationAction",
      "redClawProfileBundle": "gardenFlowProfileBundle",
      "redClawProjectContext": "gardenFlowProjectContext",
      "redClawRunnerListenersAttached": "gardenFlowRunnerListenersAttached",
      "redClawTaskStats": "gardenFlowTaskStats",
      "redClawTitleBarActions": "gardenFlowTitleBarActions",
      "redbox": "gardenflow",
      "redboxAction": "gardenflowAction",
      "redboxAuthService": "gardenflowAuthService",
      "redboxBrowserControlNativeHostStatus": "gardenflowBrowserControlNativeHostStatus",
      "redboxBrowserControlScrapers": "gardenflowBrowserControlScrapers",
      "redboxBrowserControlSettings": "gardenflowBrowserControlSettings",
      "redboxBrowserControlSidePanelOpenWindowIds": "gardenflowBrowserControlSidePanelOpenWindowIds",
      "redboxBrowserRuntime": "gardenflowBrowserRuntime",
      "redboxCaptureCheckpoints": "gardenflowCaptureCheckpoints",
      "redboxFetch": "gardenflowFetch",
      "redboxInjected": "gardenflowInjected",
      "redboxNoteKey": "gardenflowNoteKey",
      "redboxPid": "gardenflowPid",
      "redboxPluginDiagnosticsQueue": "gardenflowPluginDiagnosticsQueue",
      "redboxPluginDiagnosticsRecent": "gardenflowPluginDiagnosticsRecent",
      "redboxPluginSettings": "gardenflowPluginSettings",
      "redboxPreviousPosition": "gardenflowPreviousPosition",
      "redboxStderr": "gardenflowStderr",
      "redboxXhrOpen": "gardenflowXhrOpen",
      "redboxXhrSend": "gardenflowXhrSend",
      "redbox_editor": "gardenflow_editor",
      "redbox_official_auto": "gardenflow_official_auto",
      "redclaw": "gardenflow",
      "redclawAction": "gardenflowAction",
      "redclawAttachmentActions": "gardenflowAttachmentActions",
      "redclawAuthoring": "gardenflowAuthoring",
      "redclawBackgroundRunner": "gardenflowBackgroundRunner",
      "redclawBridge": "gardenflowBridge",
      "redclawCompactTargetTokens": "gardenflowCompactTargetTokens",
      "redclawCompleted": "gardenflowCompleted",
      "redclawContext": "gardenflowContext",
      "redclawFailed": "gardenflowFailed",
      "redclawItems": "gardenflowItems",
      "redclawOnboardingCompleted": "gardenflowOnboardingCompleted",
      "redclawOnboardingState": "gardenflowOnboardingState",
      "redclawOnboardingVersion": "gardenflowOnboardingVersion",
      "redclawOrchestration": "gardenflowOrchestration",
      "redclawOrder": "gardenflowOrder",
      "redclawProfile": "gardenflowProfile",
      "redclawProfileDirty": "gardenflowProfileDirty",
      "redclawProfileDirtyRef": "gardenflowProfileDirtyRef",
      "redclawProfileDraft": "gardenflowProfileDraft",
      "redclawProfileLoadRequestRef": "gardenflowProfileLoadRequestRef",
      "redclawProfileMessage": "gardenflowProfileMessage",
      "redclawProfileRoot": "gardenflowProfileRoot",
      "redclawProfileStore": "gardenflowProfileStore",
      "redclawProjectId": "gardenflowProjectId",
      "redclawProjects": "gardenflowProjects",
      "redclawRunner": "gardenflowRunner",
      "redclawStore": "gardenflowStore",
      "redclawTaskCompat": "gardenflowTaskCompat",
      "redclawTaskResult": "gardenflowTaskResult",
      "redclawTool": "gardenflowTool",
      "redclawUpdatedAt": "gardenflowUpdatedAt",
      "redclawVisible": "gardenflowVisible",
      "redclaw_": "gardenflow_",
      "redclaw_agent_md": "gardenflow_agent_md",
      "redclaw_bootstrap": "gardenflow_bootstrap",
      "redclaw_compact_target_tokens": "gardenflow_compact_target_tokens",
      "redclaw_create_project": "gardenflow_create_project",
      "redclaw_creator_profile_md": "gardenflow_creator_profile_md",
      "redclaw_identity_md": "gardenflow_identity_md",
      "redclaw_list_projects": "gardenflow_list_projects",
      "redclaw_path": "gardenflow_path",
      "redclaw_profile_path": "gardenflow_profile_path",
      "redclaw_projects": "gardenflow_projects",
      "redclaw_prompt": "gardenflow_prompt",
      "redclaw_runner_status": "gardenflow_runner_status",
      "redclaw_save_copy_pack": "gardenflow_save_copy_pack",
      "redclaw_save_image_pack": "gardenflow_save_image_pack",
      "redclaw_save_retrospective": "gardenflow_save_retrospective",
      "redclaw_soul_md": "gardenflow_soul_md",
      "redclaw_task_draft": "gardenflow_task_draft",
      "redclaw_task_submitted": "gardenflow_task_submitted",
      "redclaw_update_creator_profile": "gardenflow_update_creator_profile",
      "redclaw_update_profile_doc": "gardenflow_update_profile_doc",
      "redclaw_user_md": "gardenflow_user_md",
      "redconvert": "gardenflow",
      "resetRedclawProfileState": "resetGardenFlowProfileState",
      "resolveRedClawAttachmentShortcutScene": "resolveGardenFlowAttachmentShortcutScene",
      "resolveRedClawComposerShortcutScene": "resolveGardenFlowComposerShortcutScene",
      "resolveRedClawRoot": "resolveGardenFlowRoot",
      "restrictToAppCliInRedClaw": "restrictToAppCliInGardenFlow",
      "runRedClawTask": "runGardenFlowTask",
      "saveAdvisorFromRedClaw": "saveAdvisorFromGardenFlow",
      "saveRedClawCopyPack": "saveGardenFlowCopyPack",
      "saveRedClawImagePack": "saveGardenFlowImagePack",
      "saveRedClawInitializationProgress": "saveGardenFlowInitializationProgress",
      "saveRedClawRetrospective": "saveGardenFlowRetrospective",
      "saveToRedBox": "saveToGardenFlow",
      "saveToRedboxByDefault": "saveToGardenFlowByDefault",
      "savedRedclawProfileDraft": "savedGardenFlowProfileDraft",
      "selectCompatibleBojinReleaseAsset": "selectCompatibleGardenFlowReleaseAsset",
      "session_redclaw_main_": "session_gardenflow_main_",
      "setIsRedClawChatExecuting": "setIsGardenFlowChatExecuting",
      "setIsRedclawProfileLoading": "setIsGardenFlowProfileLoading",
      "setPendingRedClawMessage": "setPendingGardenFlowMessage",
      "setRedClawGlobalSidebarContent": "setGardenFlowGlobalSidebarContent",
      "setRedClawNavigationAction": "setGardenFlowNavigationAction",
      "setRedClawTitleBarActions": "setGardenFlowTitleBarActions",
      "setRedclawOnboardingState": "setGardenFlowOnboardingState",
      "setRedclawOnboardingVersion": "setGardenFlowOnboardingVersion",
      "setRedclawProfileDirty": "setGardenFlowProfileDirty",
      "setRedclawProfileDirtyState": "setGardenFlowProfileDirtyState",
      "setRedclawProfileDraft": "setGardenFlowProfileDraft",
      "setRedclawProfileMessage": "setGardenFlowProfileMessage",
      "setRedclawProfileRoot": "setGardenFlowProfileRoot",
      "setSavedRedclawProfileDraft": "setSavedGardenFlowProfileDraft",
      "shouldHandleRedClawOnboarding": "shouldHandleGardenFlowOnboarding",
      "sortRedClawAutomationItems": "sortGardenFlowAutomationItems",
      "startCreateInRedClaw": "startCreateInGardenFlow",
      "startRedClawStyleDefinition": "startGardenFlowStyleDefinition",
      "syncRedBoxMediaLibrary": "syncGardenFlowMediaLibrary",
      "syncRedBoxSettings": "syncGardenFlowSettings",
      "syncRedBoxTimelineProject": "syncGardenFlowTimelineProject",
      "syncRedBoxTimelineSettings": "syncGardenFlowTimelineSettings",
      "toRedboxAssetUrl": "toGardenFlowAssetUrl",
      "u0000redclaw": "u0000gardenflow",
      "updateRedClawCreatorProfile": "updateGardenFlowCreatorProfile",
      "updateRedClawProfileDocument": "updateGardenFlowProfileDocument",
      "updateRedClawTask": "updateGardenFlowTask",
      "useRedClawShellNavigation": "useGardenFlowShellNavigation",
      "writeRedClawLastSessionId": "writeGardenFlowLastSessionId",
      "ensureXwowAppServer": "ensureGardenFlowAppServer",
      "faviconBadgeXwowStates": "faviconBadgeGardenFlowStates",
      "ensure_xwow_app_server": "ensure_gardenflow_app_server",
      "__xwowFileChooserTrapMain": "__gardenflowFileChooserTrapMain",
      "__xwowFileChooserTrap": "__gardenflowFileChooserTrap",
      "createdByXwow": "createdByGardenFlow"
    },
    "values": {
      "Beav-9.9.9-x64.exe": "GardenFlow-9.9.9-x64.exe",
      "Bojin": "GardenFlow",
      "Bojin-2.5.1-arm64.exe": "GardenFlow-2.5.1-arm64.exe",
      "Bojin-2.5.1-x64.exe": "GardenFlow-2.5.1-x64.exe",
      "Bojin-2.5.1-x64.exe.blockmap": "GardenFlow-2.5.1-x64.exe.blockmap",
      "REDCONVERT_IMAGE_TIMEOUT_MS": "GARDENFLOW_IMAGE_TIMEOUT_MS",
      "RedBox": "GardenFlow",
      "RedBox-9.9.9-x64.exe": "GardenFlow-9.9.9-x64.exe",
      "RedBoxVideoMotion": "GardenFlowVideoMotion",
      "RedClaw": "GardenFlow",
      "RedConvert": "GardenFlow",
      "__REDBOX_CAPTURE_RUNTIME__": "__GARDENFLOW_CAPTURE_RUNTIME__",
      "__REDBOX_XHS_BRIDGE_INSTALLED__": "__GARDENFLOW_XHS_BRIDGE_INSTALLED__",
      "__REDBOX_XHS_RESPONSES__": "__GARDENFLOW_XHS_RESPONSES__",
      "__RED_ELECTRON_IPC__": "__GARDENFLOW_ELECTRON_IPC__",
      "__redboxGenericCaptureListenerV1__": "__gardenflowGenericCaptureListenerV1__",
      "__redboxPageRouteBridgeInstalled__": "__gardenflowPageRouteBridgeInstalled__",
      "__redbox_ipc_timeout__": "__gardenflow_ipc_timeout__",
      "beav": "gardenflow",
      "beav-desktop-bridge-client-": "gardenflow-desktop-bridge-client-",
      "bojin": "gardenflow",
      "bojin-asr-plus": "gardenflow-asr-plus",
      "bojin-browser-native-host.exe": "gardenflow-browser-native-host.exe",
      "bojin-capture-bridge-": "gardenflow-capture-bridge-",
      "bojin-image-3.0": "gardenflow-image-3.0",
      "bojin-imgae-2.0": "gardenflow-imgae-2.0",
      "bojin-imgae-3.0": "gardenflow-imgae-3.0",
      "bojin-key": "gardenflow-key",
      "bojin-max": "gardenflow-max",
      "bojin-native-host-reconnect-": "gardenflow-native-host-reconnect-",
      "bojin-omni-plus": "gardenflow-omni-plus",
      "bojin-plus": "gardenflow-plus",
      "bojin-speech": "gardenflow-speech",
      "bojin-text-embedding": "gardenflow-text-embedding",
      "bojin-video-1.1-r2v": "gardenflow-video-1.1-r2v",
      "bojin-video-H3": "gardenflow-video-H3",
      "bojin-video-unknown": "gardenflow-video-unknown",
      "bojin.png": "gardenflow.png",
      "bojin_official_auto": "gardenflow_official_auto",
      "com.redbox.app": "com.gardenflow.app",
      "com.redbox.browser_control": "com.gardenflow.browser_control",
      "manual:redclaw": "manual:gardenflow",
      "model_name_redclaw": "model_name_gardenflow",
      "nav_to_redclaw": "nav_to_gardenflow",
      "open-redbox-side-panel": "open-gardenflow-side-panel",
      "open-redclaw": "open-gardenflow",
      "promote-redclaw": "promote-gardenflow",
      "red-convert-desktop": "gardenflow-desktop",
      "redbox": "gardenflow",
      "redbox-asset": "gardenflow-asset",
      "redbox-auth:bootstrap": "gardenflow-auth:bootstrap",
      "redbox-auth:call-records": "gardenflow-auth:call-records",
      "redbox-auth:create-page-pay-order": "gardenflow-auth:create-page-pay-order",
      "redbox-auth:get-config": "gardenflow-auth:get-config",
      "redbox-auth:login-sms": "gardenflow-auth:login-sms",
      "redbox-auth:logout": "gardenflow-auth:logout",
      "redbox-auth:me": "gardenflow-auth:me",
      "redbox-auth:open-payment-form": "gardenflow-auth:open-payment-form",
      "redbox-auth:order-status": "gardenflow-auth:order-status",
      "redbox-auth:panel-display": "gardenflow-auth:panel-display",
      "redbox-auth:points": "gardenflow-auth:points",
      "redbox-auth:pricing": "gardenflow-auth:pricing",
      "redbox-auth:pricing-refresh": "gardenflow-auth:pricing-refresh",
      "redbox-auth:product": "gardenflow-auth:product",
      "redbox-auth:products": "gardenflow-auth:products",
      "redbox-auth:refresh": "gardenflow-auth:refresh",
      "redbox-auth:register-sms": "gardenflow-auth:register-sms",
      "redbox-auth:send-sms-code": "gardenflow-auth:send-sms-code",
      "redbox-auth:set-realm": "gardenflow-auth:set-realm",
      "redbox-auth:wechat-status": "gardenflow-auth:wechat-status",
      "redbox-auth:wechat-url": "gardenflow-auth:wechat-url",
      "redbox-browser-binding-": "gardenflow-browser-binding-",
      "redbox-browser-control": "gardenflow-browser-control",
      "redbox-browser-control-native-reconnect": "gardenflow-browser-control-native-reconnect",
      "redbox-browser-control-poll": "gardenflow-browser-control-poll",
      "redbox-browser-control:": "gardenflow-browser-control:",
      "redbox-browser-e2e-": "gardenflow-browser-e2e-",
      "redbox-browser-extension": "gardenflow-browser-extension",
      "redbox-browser-faults-": "gardenflow-browser-faults-",
      "redbox-capture": "gardenflow-capture",
      "redbox-composite": "gardenflow-composite",
      "redbox-file": "gardenflow-file",
      "redbox-image-dropzone-host": "gardenflow-image-dropzone-host",
      "redbox-motion": "gardenflow-motion",
      "redbox-official": "gardenflow-official",
      "redbox-page-route-bridge": "gardenflow-page-route-bridge",
      "redbox-plugin-auto-update-check": "gardenflow-plugin-auto-update-check",
      "redbox-plugin-diagnostics-retry": "gardenflow-plugin-diagnostics-retry",
      "redbox-project": "gardenflow-project",
      "redbox-root": "gardenflow-root",
      "redbox-runtime": "gardenflow-runtime",
      "redbox-runtime-session": "gardenflow-runtime-session",
      "redbox-save-image": "gardenflow-save-image",
      "redbox-save-link": "gardenflow-save-link",
      "redbox-save-page-auto": "gardenflow-save-page-auto",
      "redbox-save-selection": "gardenflow-save-selection",
      "redbox-save-video": "gardenflow-save-video",
      "redbox-stt-": "gardenflow-stt-",
      "redbox-video-director": "gardenflow-video-director",
      "redbox-xhs-bridge": "gardenflow-xhs-bridge",
      "redbox-xhs-card-btn": "gardenflow-xhs-card-btn",
      "redbox-xhs-detail-actions": "gardenflow-xhs-detail-actions",
      "redbox-xhs-dom-style": "gardenflow-xhs-dom-style",
      "redbox-xhs-explore": "gardenflow-xhs-explore",
      "redbox-xhs-profile-actions": "gardenflow-xhs-profile-actions",
      "redbox-xhs-status": "gardenflow-xhs-status",
      "redbox.acp.discovery.v1": "gardenflow.acp.discovery.v1",
      "redbox.acp.v1": "gardenflow.acp.v1",
      "redbox.browserPluginDiagnostic.v1": "gardenflow.browserPluginDiagnostic.v1",
      "redbox.creator-agent": "gardenflow.creator-agent",
      "redbox:app-onboarding:v1:acquisition-source": "gardenflow:app-onboarding:v1:acquisition-source",
      "redbox:app-onboarding:v1:seen": "gardenflow:app-onboarding:v1:seen",
      "redbox:app-onboarding:v2:seen": "gardenflow:app-onboarding:v2:seen",
      "redbox:app-onboarding:v2:seen-at": "gardenflow:app-onboarding:v2:seen-at",
      "redbox:app-shell:last-view:v1": "gardenflow:app-shell:last-view:v1",
      "redbox:chat:attachment-draft:v1": "gardenflow:chat:attachment-draft:v1",
      "redbox:clipboard-capture-dedupe:v1": "gardenflow:clipboard-capture-dedupe:v1",
      "redbox:cover-templates:v1": "gardenflow:cover-templates:v1",
      "redbox:custom-theme-changed": "gardenflow:custom-theme-changed",
      "redbox:custom-theme:v1": "gardenflow:custom-theme:v1",
      "redbox:feedback-report-submitted": "gardenflow:feedback-report-submitted",
      "redbox:file-index-dashboard:v1": "gardenflow:file-index-dashboard:v1",
      "redbox:generation-studio:feed:deleted:v1": "gardenflow:generation-studio:feed:deleted:v1",
      "redbox:generation-studio:feed:v1": "gardenflow:generation-studio:feed:v1",
      "redbox:generic-capture": "gardenflow:generic-capture",
      "redbox:global-knowledge-search": "gardenflow:global-knowledge-search",
      "redbox:global-knowledge-search-query": "gardenflow:global-knowledge-search-query",
      "redbox:language:v1": "gardenflow:language:v1",
      "redbox:layout-sidebar-collapsed:v1": "gardenflow:layout-sidebar-collapsed:v1",
      "redbox:layout-sidebar-width:v1": "gardenflow:layout-sidebar-width:v1",
      "redbox:locationchange": "gardenflow:locationchange",
      "redbox:navigate": "gardenflow:navigate",
      "redbox:notifications:server:v1": "gardenflow:notifications:server:v1",
      "redbox:open-feedback-report": "gardenflow:open-feedback-report",
      "redbox:redclaw-ai-surface:v1": "gardenflow:gardenflow-ai-surface:v1",
      "redbox:redclaw:hidden-external-session-ids:v1": "gardenflow:gardenflow:hidden-external-session-ids:v1",
      "redbox:redclaw:pinned-room-ids:v1": "gardenflow:gardenflow:pinned-room-ids:v1",
      "redbox:redclaw:pinned-session-ids:v1": "gardenflow:gardenflow:pinned-session-ids:v1",
      "redbox:show-current-release-notes": "gardenflow:show-current-release-notes",
      "redbox:team-active-member:": "gardenflow:team-active-member:",
      "redbox:team-member-order:": "gardenflow:team-member-order:",
      "redbox:team-section:v1": "gardenflow:team-section:v1",
      "redbox:team-workbench-snapshot:": "gardenflow:team-workbench-snapshot:",
      "redbox:theme-mode:v1": "gardenflow:theme-mode:v1",
      "redbox:ui-debug": "gardenflow:ui-debug",
      "redbox:update-notice-shown-version:v1": "gardenflow:update-notice-shown-version:v1",
      "redboxBrowserControlNativeHostStatus": "gardenflowBrowserControlNativeHostStatus",
      "redboxBrowserControlScrapers": "gardenflowBrowserControlScrapers",
      "redboxBrowserControlSettings": "gardenflowBrowserControlSettings",
      "redboxBrowserControlSidePanelOpenWindowIds": "gardenflowBrowserControlSidePanelOpenWindowIds",
      "redboxCaptureCheckpoints": "gardenflowCaptureCheckpoints",
      "redboxPluginDiagnosticsQueue": "gardenflowPluginDiagnosticsQueue",
      "redboxPluginDiagnosticsRecent": "gardenflowPluginDiagnosticsRecent",
      "redboxPluginSettings": "gardenflowPluginSettings",
      "redbox_editor": "gardenflow_editor",
      "redbox_official_auto": "gardenflow_official_auto",
      "redclaw": "gardenflow",
      "redclaw-background-runner": "gardenflow-background-runner",
      "redclaw-draft": "gardenflow-draft",
      "redclaw-heartbeat": "gardenflow-heartbeat",
      "redclaw-manuscript-list": "gardenflow-manuscript-list",
      "redclaw-note": "gardenflow-note",
      "redclaw-preview-sidebar--closing": "gardenflow-preview-sidebar--closing",
      "redclaw-preview-sidebar--open": "gardenflow-preview-sidebar--open",
      "redclaw-profile": "gardenflow-profile",
      "redclaw-project": "gardenflow-project",
      "redclaw-runner": "gardenflow-runner",
      "redclaw-singleton": "gardenflow-singleton",
      "redclaw-singleton:": "gardenflow-singleton:",
      "redclaw-style-definition": "gardenflow-style-definition",
      "redclaw-xhs-note-": "gardenflow-xhs-note-",
      "redclaw-xiaohongshu-material-package": "gardenflow-xiaohongshu-material-package",
      "redclaw.open": "gardenflow.open",
      "redclaw.profile.bundle": "gardenflow.profile.bundle",
      "redclaw.profile.completeStyleDefinition": "gardenflow.profile.completeStyleDefinition",
      "redclaw.profile.read": "gardenflow.profile.read",
      "redclaw.profile.update": "gardenflow.profile.update",
      "redclaw.task.": "gardenflow.task.",
      "redclaw:get-project": "gardenflow:get-project",
      "redclaw:learning-candidate-update": "gardenflow:learning-candidate-update",
      "redclaw:list-projects": "gardenflow:list-projects",
      "redclaw:media-plan-export": "gardenflow:media-plan-export",
      "redclaw:media-plan-render": "gardenflow:media-plan-render",
      "redclaw:open-project": "gardenflow:open-project",
      "redclaw:orchestration-create-run": "gardenflow:orchestration-create-run",
      "redclaw:orchestration-registry": "gardenflow:orchestration-registry",
      "redclaw:profile:complete-initialization": "gardenflow:profile:complete-initialization",
      "redclaw:profile:complete-style-definition": "gardenflow:profile:complete-style-definition",
      "redclaw:profile:get-bundle": "gardenflow:profile:get-bundle",
      "redclaw:profile:onboarding-status": "gardenflow:profile:onboarding-status",
      "redclaw:profile:onboarding-turn": "gardenflow:profile:onboarding-turn",
      "redclaw:profile:save-initialization-progress": "gardenflow:profile:save-initialization-progress",
      "redclaw:profile:start-style-definition": "gardenflow:profile:start-style-definition",
      "redclaw:profile:update-doc": "gardenflow:profile:update-doc",
      "redclaw:project-section-update": "gardenflow:project-section-update",
      "redclaw:publish-package-export": "gardenflow:publish-package-export",
      "redclaw:review-report-export": "gardenflow:review-report-export",
      "redclaw:runner-add-long-cycle": "gardenflow:runner-add-long-cycle",
      "redclaw:runner-add-scheduled": "gardenflow:runner-add-scheduled",
      "redclaw:runner-builtin-readiness": "gardenflow:runner-builtin-readiness",
      "redclaw:runner-install-builtin-mcp": "gardenflow:runner-install-builtin-mcp",
      "redclaw:runner-list-builtin": "gardenflow:runner-list-builtin",
      "redclaw:runner-list-long-cycle": "gardenflow:runner-list-long-cycle",
      "redclaw:runner-list-scheduled": "gardenflow:runner-list-scheduled",
      "redclaw:runner-log": "gardenflow:runner-log",
      "redclaw:runner-message": "gardenflow:runner-message",
      "redclaw:runner-remove-long-cycle": "gardenflow:runner-remove-long-cycle",
      "redclaw:runner-remove-scheduled": "gardenflow:runner-remove-scheduled",
      "redclaw:runner-run-builtin-now": "gardenflow:runner-run-builtin-now",
      "redclaw:runner-run-long-cycle-now": "gardenflow:runner-run-long-cycle-now",
      "redclaw:runner-run-now": "gardenflow:runner-run-now",
      "redclaw:runner-run-scheduled-now": "gardenflow:runner-run-scheduled-now",
      "redclaw:runner-set-builtin-enabled": "gardenflow:runner-set-builtin-enabled",
      "redclaw:runner-set-builtin-settings": "gardenflow:runner-set-builtin-settings",
      "redclaw:runner-set-config": "gardenflow:runner-set-config",
      "redclaw:runner-set-long-cycle-enabled": "gardenflow:runner-set-long-cycle-enabled",
      "redclaw:runner-set-project": "gardenflow:runner-set-project",
      "redclaw:runner-set-scheduled-enabled": "gardenflow:runner-set-scheduled-enabled",
      "redclaw:runner-start": "gardenflow:runner-start",
      "redclaw:runner-status": "gardenflow:runner-status",
      "redclaw:runner-stop": "gardenflow:runner-stop",
      "redclaw:task-cancel": "gardenflow:task-cancel",
      "redclaw:task-confirm": "gardenflow:task-confirm",
      "redclaw:task-create": "gardenflow:task-create",
      "redclaw:task-event": "gardenflow:task-event",
      "redclaw:task-list": "gardenflow:task-list",
      "redclaw:task-preview": "gardenflow:task-preview",
      "redclaw:task-stats": "gardenflow:task-stats",
      "redclaw:task-update": "gardenflow:task-update",
      "redclaw:team-settings-changed": "gardenflow:team-settings-changed",
      "redclaw:xhs-package-export": "gardenflow:xhs-package-export",
      "redclaw_create_project": "gardenflow_create_project",
      "redclaw_list_projects": "gardenflow_list_projects",
      "redclaw_prompt": "gardenflow_prompt",
      "redclaw_runner_status": "gardenflow_runner_status",
      "redclaw_save_copy_pack": "gardenflow_save_copy_pack",
      "redclaw_save_image_pack": "gardenflow_save_image_pack",
      "redclaw_save_retrospective": "gardenflow_save_retrospective",
      "redclaw_task_draft": "gardenflow_task_draft",
      "redclaw_task_submitted": "gardenflow_task_submitted",
      "redclaw_update_creator_profile": "gardenflow_update_creator_profile",
      "redclaw_update_profile_doc": "gardenflow_update_profile_doc",
      "redconvert": "gardenflow",
      "redconvert-cli": "gardenflow-cli",
      "redconvert-desktop": "gardenflow-desktop",
      "redconvert.db": "gardenflow.db",
      "redconvert:feature-flags": "gardenflow:feature-flags",
      "video-provider-bojin": "video-provider-gardenflow",
      "Bojin官方": "GardenFlow官方",
      "Bojin私有网关": "GardenFlow私有网关",
      "Bojin Seedance": "GardenFlow Seedance",
      "bojin-vl-embedding": "gardenflow-vl-embedding",
      "ensureXwowAppServer": "ensureGardenFlowAppServer",
      "xwow-data-ai:native-connect": "gardenflow-data-ai:native-connect",
      "xwow-data-ai:": "gardenflow-data-ai:",
      "xwow-browser-data-ai": "gardenflow-browser-data-ai",
      "xwow-browser-data-ai-control-badge": "gardenflow-browser-data-ai-control-badge",
      "xwow-data-ai:content-ping": "gardenflow-data-ai:content-ping",
      "xwowBrowserDataAiTabLeases": "gardenflowBrowserDataAiTabLeases",
      "xwowBrowserDataAiTabGroups": "gardenflowBrowserDataAiTabGroups",
      "xwowBrowserDataAiFinalizedTabBadges": "gardenflowBrowserDataAiFinalizedTabBadges",
      "xwow_action_time_extension": "gardenflow_action_time_extension",
      "xwowBrowserDataAiPendingUpdateVersion": "gardenflowBrowserDataAiPendingUpdateVersion",
      "xwow-browser-data-ai-client-heartbeat": "gardenflow-browser-data-ai-client-heartbeat",
      "xwowBrowserDataAiClientHeartbeatState": "gardenflowBrowserDataAiClientHeartbeatState",
      "xwowBrowserDataAiLifecycleCleanupResult": "gardenflowBrowserDataAiLifecycleCleanupResult",
      "xwowBrowserDataAiSidePanelOpenWindowIds": "gardenflowBrowserDataAiSidePanelOpenWindowIds",
      "open-xwow-side-panel": "open-gardenflow-side-panel",
      "ensure_xwow_app_server": "ensure_gardenflow_app_server",
      "com.xwow.browser_data_ai": "com.gardenflow.browser_data_ai",
      "xwow-browser-data-ai-native-reconnect": "gardenflow-browser-data-ai-native-reconnect",
      "xwowBrowserDataAiNativeHostStatus": "gardenflowBrowserDataAiNativeHostStatus",
      "xwow_diagnostics_extension": "gardenflow_diagnostics_extension",
      "xwow_operator_extension": "gardenflow_operator_extension",
      "xwowBrowserDataAiBrowserEvents": "gardenflowBrowserDataAiBrowserEvents",
      "xwow_target_method_normalizers": "gardenflow_target_method_normalizers",
      "xwowBrowserDataAiSessions": "gardenflowBrowserDataAiSessions",
      "xwowBrowserDataAiSessionEvents": "gardenflowBrowserDataAiSessionEvents",
      "xwowBrowserDataAiCdpEvents": "gardenflowBrowserDataAiCdpEvents",
      "xwowBrowserDataAiViewportRestore": "gardenflowBrowserDataAiViewportRestore",
      "xwowBrowserDataAiDownloadEvents": "gardenflowBrowserDataAiDownloadEvents",
      "xwowBrowserDataAiDownloadState": "gardenflowBrowserDataAiDownloadState",
      "xwow-data-ai:file-chooser-opened": "gardenflow-data-ai:file-chooser-opened",
      "xwow-data-ai:file-chooser-trap": "gardenflow-data-ai:file-chooser-trap",
      "data-xwow-file-chooser-payload": "data-gardenflow-file-chooser-payload",
      "xwow-data-ai:page-assets": "gardenflow-data-ai:page-assets",
      "xwow-data-ai:cursor-move": "gardenflow-data-ai:cursor-move",
      "xwow-data-ai:cursor-hide": "gardenflow-data-ai:cursor-hide",
      "xwow-data-ai:cursor-arrived": "gardenflow-data-ai:cursor-arrived",
      "xwow-data-ai:control-badge": "gardenflow-data-ai:control-badge",
      "xwow-favicon-badge": "gardenflow-favicon-badge",
      "xwow-data-ai:read-frame": "gardenflow-data-ai:read-frame",
      "xwow-data-ai:dom-snapshot": "gardenflow-data-ai:dom-snapshot",
      "xwow-data-ai:site-research-extract": "gardenflow-data-ai:site-research-extract",
      "xwow-data-ai:site-research-apply-filters": "gardenflow-data-ai:site-research-apply-filters",
      "xwow-data-ai:site-research-submit-search": "gardenflow-data-ai:site-research-submit-search",
      "xwow-data-ai:site-research-prepare-item-click": "gardenflow-data-ai:site-research-prepare-item-click",
      "xwow-data-ai:site-research-prepare-item-close": "gardenflow-data-ai:site-research-prepare-item-close",
      "xwow-data-ai:scroll-page": "gardenflow-data-ai:scroll-page",
      "xwow-data-ai:click-next": "gardenflow-data-ai:click-next",
      "xwow-data-ai:click-element": "gardenflow-data-ai:click-element",
      "xwow-data-ai:click-node": "gardenflow-data-ai:click-node",
      "xwow-data-ai:hover-element": "gardenflow-data-ai:hover-element",
      "xwow-data-ai:inspect-point": "gardenflow-data-ai:inspect-point",
      "xwow-data-ai:scroll-node": "gardenflow-data-ai:scroll-node",
      "xwow-data-ai:select-element": "gardenflow-data-ai:select-element",
      "xwow-data-ai:type-element": "gardenflow-data-ai:type-element",
      "xwow-data-ai:wait-stable": "gardenflow-data-ai:wait-stable",
      "xwow-data-ai:wait-selector": "gardenflow-data-ai:wait-selector",
      "xwow-data-ai:wait-node": "gardenflow-data-ai:wait-node",
      "xwow-data-ai:check-element": "gardenflow-data-ai:check-element",
      "xwow-data-ai:is-checked": "gardenflow-data-ai:is-checked",
      "xwow-data-ai:is-visible": "gardenflow-data-ai:is-visible",
      "xwow-data-ai:get-value": "gardenflow-data-ai:get-value",
      "xwow-data-ai:get-values": "gardenflow-data-ai:get-values",
      "xwow-data-ai:get-attribute": "gardenflow-data-ai:get-attribute",
      "xwow-data-ai:query-elements": "gardenflow-data-ai:query-elements",
      "xwow-data-ai:get-status": "gardenflow-data-ai:get-status",
      "xwow-data-ai:get-active-tab": "gardenflow-data-ai:get-active-tab",
      "xwow-data-ai:register": "gardenflow-data-ai:register",
      "xwow-data-ai:analyze-active-tab": "gardenflow-data-ai:analyze-active-tab",
      "xwow-data-ai:suggest-columns": "gardenflow-data-ai:suggest-columns",
      "xwow-data-ai:preview-active-tab": "gardenflow-data-ai:preview-active-tab",
      "xwow-data-ai:run-scraper": "gardenflow-data-ai:run-scraper",
      "xwow-data-ai:stop-run": "gardenflow-data-ai:stop-run",
      "xwow-data-ai:create-browser-session": "gardenflow-data-ai:create-browser-session",
      "xwow-data-ai:list-browser-sessions": "gardenflow-data-ai:list-browser-sessions",
      "xwow-data-ai:end-browser-session": "gardenflow-data-ai:end-browser-session",
      "xwow-data-ai:run-browser-action": "gardenflow-data-ai:run-browser-action",
      "xwow-data-ai:native-status": "gardenflow-data-ai:native-status",
      "xwow-data-ai:native-disconnect": "gardenflow-data-ai:native-disconnect",
      "xwow-data-ai:native-request": "gardenflow-data-ai:native-request",
      "xwow-data-ai:side-panel-status": "gardenflow-data-ai:side-panel-status",
      "xwow-data-ai:side-panel-open": "gardenflow-data-ai:side-panel-open",
      "xwow-data-ai:side-panel-close": "gardenflow-data-ai:side-panel-close",
      "xwow-data-ai:side-panel-toggle": "gardenflow-data-ai:side-panel-toggle",
      "xwow-data-ai:save-scraper": "gardenflow-data-ai:save-scraper",
      "xwow-data-ai:list-scrapers": "gardenflow-data-ai:list-scrapers",
      "xwow-data-ai:list-captures": "gardenflow-data-ai:list-captures",
      "xwow-data-ai:list-commands": "gardenflow-data-ai:list-commands",
      "xwow-data-ai:poll-command": "gardenflow-data-ai:poll-command",
      "xwow-data-ai:capture-active-tab": "gardenflow-data-ai:capture-active-tab",
      "xwow-data-ai:ingest-manual-capture": "gardenflow-data-ai:ingest-manual-capture",
      "xwow-browser-data-ai-control-badge-style": "gardenflow-browser-data-ai-control-badge-style",
      "xwow-browser-data-ai-cursor": "gardenflow-browser-data-ai-cursor",
      "xwow-browser-data-ai-cursor-style": "gardenflow-browser-data-ai-cursor-style",
      "native://redbox": "native://gardenflow",
      "native://redconvert": "native://gardenflow"
    },
    "environment": {
      "REDBOX_ALLOW_SYSTEM_FFMPEG": "GARDENFLOW_ALLOW_SYSTEM_FFMPEG",
      "REDBOX_BROWSER_BRIDGE_DESCRIPTOR": "GARDENFLOW_BROWSER_BRIDGE_DESCRIPTOR",
      "REDBOX_BROWSER_CONTROL_AGENT_TIMEOUT_MS": "GARDENFLOW_BROWSER_CONTROL_AGENT_TIMEOUT_MS",
      "REDBOX_BROWSER_CONTROL_API": "GARDENFLOW_BROWSER_CONTROL_API",
      "REDBOX_BROWSER_CONTROL_CHROME_PATH": "GARDENFLOW_BROWSER_CONTROL_CHROME_PATH",
      "REDBOX_BROWSER_CONTROL_ENDPOINTS_DIRECTORY": "GARDENFLOW_BROWSER_CONTROL_ENDPOINTS_DIRECTORY",
      "REDBOX_BROWSER_CONTROL_ENDPOINT_STATE": "GARDENFLOW_BROWSER_CONTROL_ENDPOINT_STATE",
      "REDBOX_BROWSER_CONTROL_EXTENSION_ID": "GARDENFLOW_BROWSER_CONTROL_EXTENSION_ID",
      "REDBOX_BROWSER_CONTROL_HOST_PATH": "GARDENFLOW_BROWSER_CONTROL_HOST_PATH",
      "REDBOX_BROWSER_CONTROL_INSTANCE_ID": "GARDENFLOW_BROWSER_CONTROL_INSTANCE_ID",
      "REDBOX_BROWSER_CONTROL_MCP_TIMEOUT_MS": "GARDENFLOW_BROWSER_CONTROL_MCP_TIMEOUT_MS",
      "REDBOX_BROWSER_CONTROL_NODE": "GARDENFLOW_BROWSER_CONTROL_NODE",
      "REDBOX_BROWSER_CONTROL_SOCKET": "GARDENFLOW_BROWSER_CONTROL_SOCKET",
      "REDBOX_BROWSER_CONTROL_STATE_DIR": "GARDENFLOW_BROWSER_CONTROL_STATE_DIR",
      "REDBOX_ENABLE_LEGACY_PLUGIN_HTTP": "GARDENFLOW_ENABLE_LEGACY_PLUGIN_HTTP",
      "REDBOX_NATIVE_NODE": "GARDENFLOW_NATIVE_NODE",
      "REDBOX_PNPM_CLI": "GARDENFLOW_PNPM_CLI",
      "REDBOX_VIDEO_PROXY_THRESHOLD_MS": "GARDENFLOW_VIDEO_PROXY_THRESHOLD_MS",
      "REDCONVERT_ALLOW_SYSTEM_FFMPEG": "GARDENFLOW_ALLOW_SYSTEM_FFMPEG",
      "REDCONVERT_DEBUG": "GARDENFLOW_DEBUG",
      "REDCONVERT_FFMPEG_PATH": "GARDENFLOW_FFMPEG_PATH",
      "REDCONVERT_IMAGE_DEBUG": "GARDENFLOW_IMAGE_DEBUG",
      "REDCONVERT_RELAY_TOKEN": "GARDENFLOW_RELAY_TOKEN",
      "REDCONVERT_RELAY_URL": "GARDENFLOW_RELAY_URL",
      "RED_BOX_PARITY_BASELINE": "GARDENFLOW_PARITY_BASELINE",
      "REDBOX_NODE_VERSION": "GARDENFLOW_NODE_VERSION",
      "REDBOX_PNPM_VERSION": "GARDENFLOW_PNPM_VERSION",
      "REDBOX_NODE_DIST_URL": "GARDENFLOW_NODE_DIST_URL",
      "REDBOX_BROWSER_CONTROL_CLIENT_TIMEOUT_MS": "GARDENFLOW_BROWSER_CONTROL_CLIENT_TIMEOUT_MS",
      "REDBOX_BROWSER_CONTROL_ENDPOINT_STALE_MS": "GARDENFLOW_BROWSER_CONTROL_ENDPOINT_STALE_MS"
    },
    "cliExecutables": [
      "redconvert",
      "redconvert-cli"
    ],
    "contextPrefixes": {
      "redclaw-singleton:": "gardenflow-singleton:",
      "redclaw-heartbeat:": "gardenflow-heartbeat:",
      "redclaw-bg-": "gardenflow-bg-",
      "redclaw-schedule-": "gardenflow-schedule-",
      "redclaw-builtin-": "gardenflow-builtin-",
      "redclaw-long-": "gardenflow-long-"
    }
  }
};
const aliases = identity.legacy;
const opaqueFields = new Set(['content', 'text', 'prompt', 'systemPrompt', 'system_prompt', 'objective', 'stepPrompt', 'body', 'markdown', 'description', 'summary', 'title', 'reasoning', 'tool_calls', 'tool_result']);
const identityFields = new Set(['mode', 'scope', 'sourceMode', 'source', 'type', 'kind', 'provider', 'preset', 'presetId', 'preset_id', 'sourceId', 'default_ai_source_id', 'model', 'modelId', 'modelName', 'defaultModel', 'id', 'skill', 'skillName', 'forcedSkillNames', 'models', 'name', 'appSlug', 'sourceType', 'actionType', 'uiHint', 'context', 'contextKey', 'context_key', 'contextType', 'contextId', 'source_type', 'source_mode', 'scope_id', 'runtimeMode', 'runtime_mode', 'sessionType']);

function canonicalKey(value) {
    if (Object.hasOwn(aliases.keys, value)) return aliases.keys[value];
    if (Object.hasOwn(aliases.values, value)) return aliases.values[value];
    // Only qualified storage / wire identifiers use prefix aliases, never prose.
    for (const [oldKey, newKey] of Object.entries(aliases.values).sort((a, b) => b[0].length - a[0].length)) {
        if (value.startsWith(`${oldKey}:`)) return newKey + value.slice(oldKey.length);
    }
    return value;
}

function canonicalValue(value) {
    return typeof value === 'string' && Object.hasOwn(aliases.values, value) ? aliases.values[value] : value;
}

function migrateStructured(value, field = '') {
    if (ArrayBuffer.isView(value)) return value;
    if (opaqueFields.has(field) || /(?:key|token|secret|password|endpoint|url)$/i.test(field)) return value;
    if (Array.isArray(value)) return value.map(item => migrateStructured(item, field));
    if (value && typeof value === 'object') {
        const result = {};
        for (const [key, item] of Object.entries(value)) {
            const target = canonicalKey(key);
            // A deliberately saved new key takes precedence over a legacy alias.
            if (target !== key && Object.hasOwn(value, target)) continue;
            result[target] = migrateStructured(item, target);
        }
        return result;
    }
    if (typeof value !== 'string') return value;
    if (field === 'contextId') {
        for (const [oldPrefix, newPrefix] of Object.entries(aliases.contextPrefixes)) {
            if (value.startsWith(oldPrefix)) return newPrefix + value.slice(oldPrefix.length);
        }
    }
    if (field.endsWith('_json')) {
        try {
            const parsed = JSON.parse(value);
            const next = migrateStructured(parsed, field.endsWith('models_json') ? 'models' : '');
            return JSON.stringify(parsed) === JSON.stringify(next) ? value : JSON.stringify(next);
        } catch { return value; }
    }
    if (identityFields.has(field) || /^(?:model_name|.*_model)(?:_|$)/.test(field)) return canonicalKey(value);
    return value;
}

function applyEnvironmentAliases(environment) {
    for (const [oldName, newName] of Object.entries(aliases.environment)) {
        if (environment[newName] === undefined && environment[oldName] !== undefined) environment[newName] = environment[oldName];
    }
}

function migrateStorage(storage) {
    const keys = Array.from({ length: storage.length }, (_, index) => storage.key(index)).filter(Boolean);
    for (const key of keys) {
        const target = canonicalKey(key);
        if (target === key || storage.getItem(target) !== null) continue;
        const raw = storage.getItem(key);
        let next = raw;
        try { next = JSON.stringify(migrateStructured(JSON.parse(raw))); } catch { /* Keep non-JSON preferences. */ }
        storage.setItem(target, next);
    }
}

const compatibility = { identity, canonicalKey, canonicalValue, migrateStructured, applyEnvironmentAliases, migrateStorage };

export { identity, canonicalKey, canonicalValue, migrateStructured, applyEnvironmentAliases, migrateStorage };
export default compatibility;
