export {
    DEFAULT_IMAGE_HOSTING_CONFIG_ID,
    IMAGE_HOSTING_JSON_KEY,
    createDefaultGithubConfig,
    createDefaultImageHostingConfig,
    createDefaultImageHostingSettings,
    getActiveImageHostingConfig,
    isGithubImageHostingReady,
    isGithubRepoName,
    isImageHostingReady,
    normalizeImageHostingSettings,
    serializeImageHostingSettings,
    updateActiveImageHostingSettings,
    type ImageHostingConfig,
    type ImageHostingGithubConfig,
    type ImageHostingProviderType,
    type ImageHostingSettings,
    type GithubPublicUrlStyle,
} from '../../../shared/imageHosting.ts';
